"""followers

Revision ID: 752ccf41be45
Revises: a3187360c42b
Create Date: 2019-03-16 19:14:15.655881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752ccf41be45'
down_revision = 'a3187360c42b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
